### ISSUE TITLE
Update for phpBB 3.2

### ISSUE THREAD

**Issue by avandenberghe** [bbDKP/PBWoW3style#2]

**Comment by Inkoming** [comment]
You are amazing to update this style to the phpBB 3.2! It's awesome.

And what about then pbWoWext with really good improvements of the style? Will you update it too?

**Comment by Inkoming** [comment]
Three months later, we're on 21st of August. Can you give any news about maintaining the pbwow style and the pbwow_ext for the phpBB 3.2 version and WoW Legion?

**Comment by avandenberghe** [comment]
pbWoW 3.2 "base style" is now almost ready.  But the extension & derivate styles will be delivered at the same time as the base style.

**Comment by Galixte** [comment]
Good to know, thanks !

**Comment by miri4ever** [comment]
Yes I know about this Galixte. Using finally my favorite style back. Even if it has some little and some big bugs still inside.

Codebox write anything inside one line as puttinng each line for their own.
Some text inside the user control panel and some pages still can not read with wrong colors.
The background image is not fixed as it should be and moving or zooming.
Don't see the topic icons inside the posts

And recent topics extension is not looking the same way as in prosilver where are nice borders arround and everything at the same height as the forums. Maybe it's possble to do the same way as display a forum name with this +/- box when it's viewed at the right side of the forum.

And still a lot of extensions breaking a hole inside the overall header and making a gap between the style  instead of expanding just the border arround. 

The color of HR Color should be changed that it more could be seen inside postings.

Thats all for the moment I found while testing latest update.

**Comment by avandenberghe** [comment]
hey thanks for the feedback. those issues should now largely be solved.

**Comment by Galathir** [comment]
Looking good to me... though my use is fairly basic. Mostly I just wanted to say thanks for the work on this, Sajaki. It's definitely appreciated!

**Comment by miri4ever** [comment]
It's getting better and better everyday I'm looking for updates. But I still having trouble with code blocks. It just display everything inside one big line and doing no linebreaks for each line. So the code boxes getting still out of order. The style looks nice but missing the linebreaks.

The Going to Forum dropdown Menu at the far right buttom is still in grey with orange colored text and now all the buttons from the style got orange if doing mouse over ?

Third thing I noticed yesterday at your page is Recent topics having a nice dropdown box at this headline  like a menus from the style. This is looking pretty awesome and the way it should look like but mine still having this old headline with no collapse button with the latest style updates. 

Will we get the old static background without moving or zooming when browsing the forums like the old style did ?

**Comment by avandenberghe** [comment]
the codebox should be wrapping, but to make sure it does, change content.css (line 619-629) by adding "white-space: normal !important;" like below. 

```
.codebox code {
	overflow: auto;
	display: block;
	height: auto;
	max-height: 200px;
	white-space: normal !important;
	padding-top: 5px;
	font: 0.9em Monaco, "Andale Mono","Courier New", Courier, monospace;
	line-height: 1.3em;
	margin: 2px 0;
} 
```

**Comment by Inkoming** [comment]
Very happy to see the project is still maintained.
I'll sure update to 3.2 as soon as you'll release the whole package (pbwow_ext and so on...).

Glad to see you work on this. Keep it going, you're doing great work. Thanks!

**Comment by Galathir** [comment]
Hey, Sajaki... I pulled down the CSS updates from yesterday when you tweaked the forms stuff... can you point me in the right direction if I want to change the color of the buttons? I found where to change the text on the buttons, but not the buttons themselves. *is by no means a CSS guru, and is probably missing the obvious*

**Comment by miri4ever** [comment]
Ok this codebox working now on firefox fine but not with Opera. If I try on prosilver it's just fine on Opera but sometimes browsers doing crazy things and need sometimes a few hours to refresh. 

The buttons now finally looking good but they needed a lot of loading and refresh to see the result. Also the dropdownbox seems now fine.

But another strange things since last 2 updates you made sometimes topics produce a white dashed border and sometimes not. It's not really a border someting arround some topics must produce a white line. This happens sometimes on Opera and Firefox. But not all topics are affected with this, that's why I  can't explain this really.

![11](https://user-images.githubusercontent.com/16743819/29666687-a74f92f8-88d9-11e7-9330-e6f272d1cb2e.jpg)

**Comment by avandenberghe** [comment]
i'll check out the opera browser, never used it.

**Comment by avandenberghe** [comment]
codebox in Opera seems to work ok.
![screen shot 2017-08-24 at 18 00 36](https://user-images.githubusercontent.com/226730/29675726-552634d8-88f6-11e7-9aae-f09674fc67d5.png)

**Comment by avandenberghe** [comment]
If there are specific issues, please open a new topic.

**Comment by miri4ever** [comment]
As I see inside your example your version also doing no line breaks at all, For me it looks the same way but this is not right. I might searching for a better example to explain.

**Comment by avandenberghe** [comment]
regarding the codebox, in the latest release 3.2.1, it should work.

**Comment by Galixte** [comment]
Miami 3.2.1 version, thanks.

Will you add the video backgrounds to each sub styles like it was before (PayBas versions)?
